services:
  postgres:
    container_name: postgres
    image: postgres:14.15-alpine3.20
    environment:
      POSTGRES_DB: stac_db
      POSTGRES_USER: stac_user     
      POSTGRES_PASSWORD: stac_password
    volumes:
      - ./backend/postgres/data:/var/lib/postgresql/data
      - ./backend/postgres/init/init-stac-db.sql:/docker-entrypoint-initdb.d/init-stac-db.sql 
      - ./backend/postgres/init/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
    ports:
      - "5432:5432"

  node:
    build: ./backend/node
    container_name: node
    ports:
      - 3000:3000
    
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  react:
    build: ./react-app-catx/
    container_name: react
    ports:
      - 5173:5173

  adminer:
    image: adminer:latest
    container_name: db-viewer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data: