version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: stac_db
      POSTGRES_USER: stac_user     
      POSTGRES_PASSWORD: stac_password
    volumes:
      - ./postgis/postgres_data:/var/lib/postgresql/data
      - ./postgis/init-stac-db.sql:/docker-entrypoint-initdb.d/init-stac-db.sql 
      - ./postgis/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
    ports:
      - "5432:5432"

  catalogue:
    build: ./backend
    container_name: catalogue
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app/

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
