### Use with VS Code extension REST Client


### Request a token
# @name postLogin
POST http://localhost:3000/api/token
Content-Type: application/json

{
  "username": "test_user",
  "password": "password"
}

###
@token = {{postLogin.response.body.token}}
###

### Get Collections
POST http://localhost:3000/api/collections
Content-Type: application/json

{
  "limit": 10,
  "offset": 0
}

### Get keywords
POST http://localhost:3000/api/keywords
Content-Type: application/json

{
  "limit": 10,
  "offset": 0
}

### Access protected route
POST http://localhost:3000/api/collections
Authorization: Bearer {{token}}

### get items
POST http://localhost:3000/api/items
Content-Type: application/json

{
  "limit": 10,
  "offset": 0
}