CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    full_name TEXT,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role SMALLINT CHECK (
        role BETWEEN 0
        AND 2
    ) DEFAULT 0 NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATION_USER TEXT,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER TEXT
);